development:
  adapter: mysql2
  encoding: utf8
  database: westalko
  username: root
  password: 123

test:
  adapter: mysql2
  encoding: utf8
  database: westalko_test
  username: root
  password: 123

production:
  adapter: mysql2
  encoding: utf8
  database: westalko_prod
  username: root
  password: 123
